#define GLI_INCLUDE_MAIN

#include "GLCore\GLCore1_1_Include.h"
#include "GLCore\GLCore1_2_Include.h"
#include "GLCore\GLCore1_3_Include.h"
#include "GLCore\GLCore1_4_Include.h"
#include "GLCore\GLCore1_5_Include.h"
#include "GLCore\GLCore2_0_Include.h"

#include "ARB\ARB_color_buffer_float_Include.h"
#include "ARB\ARB_draw_buffers_Include.h"
#include "ARB\ARB_half_float_pixel_Include.h"
#include "ARB\ARB_multisample_Include.h"
#include "ARB\ARB_multitexture_Include.h"
#include "ARB\ARB_occlusion_query_Include.h"
#include "ARB\ARB_pixel_buffer_object_Include.h"
#include "ARB\ARB_point_parameters_Include.h"
#include "ARB\ARB_shader_objects_Include.h"
#include "ARB\ARB_shadow_ambient_Include.h"
#include "ARB\ARB_texture_compression_Include.h"
#include "ARB\ARB_texture_float_Include.h"
#include "ARB\ARB_texture_rectangle_Include.h"
#include "ARB\ARB_transpose_matrix_Include.h"
#include "ARB\ARB_vertex_blend_Include.h"
#include "ARB\ARB_vertex_buffer_object_Include.h"
#include "ARB\ARB_vertex_fragment_shader_Include.h"
#include "ARB\ARB_vertex_fragment_program_Include.h"
#include "ARB\ARB_window_pos_Include.h"

#include "ATI\ATI_draw_buffers_Include.h"
#include "ATI\ATI_envmap_bumpmap_Include.h"
#include "ATI\ATI_seperate_stencil_Include.h"
#include "ATI\ATI_texture_env_combine3_Include.h"
#include "ATI\ATI_vertex_object_Include.h"
#include "ATI\ATI_fragment_shader_Include.h"
#include "ATI\ATI_vertex_streams_Include.h"

#include "NV\NV_copy_depth_to_color_Include.h"
#include "NV\NV_depth_clamp_Include.h"
#include "NV\NV_fence_Include.h"
#include "NV\NV_float_buffer_Include.h"
#include "NV\NV_half_float_Include.h"
#include "NV\NV_multisample_filter_hint_Include.h"
#include "NV\NV_occlusion_query_Include.h"
#include "NV\NV_pixel_data_range_Include.h"
#include "NV\NV_point_sprite_Include.h"
#include "NV\NV_primitive_restart_Include.h"
#include "NV\NV_register_combiners_Include.h"
#include "NV\NV_texture_env_combine4_Include.h"
#include "NV\NV_texture_expand_normal_Include.h"
#include "NV\NV_texture_shader_Include.h"
#include "NV\NV_vertex_array_range_Include.h"
#include "NV\NV_vertex_fragment_program_Include.h"

#include "Misc\EXT_blend_Include.h"
#include "Misc\EXT_compiled_vertex_array_Include.h"
#include "Misc\EXT_depth_bounds_test_Include.h"
#include "Misc\EXT_fog_coord_Include.h"
#include "Misc\EXT_frame_buffer_object_Include.h"
#include "Misc\EXT_packed_depth_stencil_Include.h"
#include "Misc\EXT_secondary_color_Include.h"
#include "Misc\EXT_stencil_two_side_Include.h"
#include "Misc\EXT_texture3D_Include.h"
#include "Misc\EXT_draw_range_elements_Include.h"
#include "Misc\EXT_texture_compression_s3tc_Include.h"
#include "Misc\EXT_texture_filter_anisotropic_Include.h"
#include "Misc\EXT_texture_mirror_clamp_Include.h"
#include "Misc\EXT_vertex_shader_Include.h"
#include "Misc\EXT_legacy_Include.h"
#include "Misc\HP_occlusion_test_Include.h"
#include "Misc\GREMEDY_string_marker_Include.h"

#include "WGL\WGLCore_Include.h"
#include "WGL\WGL_ARB_buffer_region_Include.h"
#include "WGL\WGL_ARB_extensions_string_Include.h"
#include "WGL\WGL_ARB_make_current_read_Include.h"
#include "WGL\WGL_ARB_pbuffer_Include.h"
#include "WGL\WGL_ARB_pixel_format_Include.h"
#include "WGL\WGL_ARB_render_texture_Include.h"

#include "WGL\WGL_ATI_pixel_format_float_Include.h"
#include "WGL\WGL_EXT_swap_control_Include.h"

#include "XGL\XGLCore_Include.h"
#include "XGL\XGL_EXT_import_context_Include.h"
#include "XGL\XGL_SGI_video_sync_Include.h"
#include "XGL\XGL_SGI_swap_control_Include.h"





