#define GLI_INCLUDE_ARB_TEXTURE_RECTANGLE


enum Main {

  //GL_HALF_FLOAT_ARB                 =  0x140B,
  GL_TEXTURE_RECTANGLE_ARB          =  0x84F5,
  GL_TEXTURE_BINDING_RECTANGLE_ARB  =  0x84F6,
  GL_PROXY_TEXTURE_RECTANGLE_ARB    =  0x84F7,
  GL_MAX_RECTANGLE_TEXTURE_SIZE_ARB =  0x84F8,

};




